name: Run UnitTest
on:
  push:
    branches:
      - '*'

jobs:
  build-and-run-UnitTest:
    runs-on: any_archLinux
    steps:
      - run: git clone --depth=1 --no-single-branch https://git.seodisparate.com/stephenseo/3d_collision_helpers.git 3dchelpers
      - run: cd 3dchelpers && git checkout $GITHUB_REF_NAME
      - run: cd 3dchelpers && cmake -S . -B buildDebug
      - run: make -C 3dchelpers/buildDebug
      - run: ./3dchelpers/buildDebug/UnitTest
